/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_aznc_fibspeed_Fibonacci */

#ifndef _Included_cc_aznc_fibspeed_Fibonacci
#define _Included_cc_aznc_fibspeed_Fibonacci
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_aznc_fibspeed_Fibonacci
 * Method:    fibNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cc_aznc_fibspeed_Fibonacci_fibNative
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
